"""Initial migration

Revision ID: 3296b4e43075
Revises: 
Create Date: 2026-01-19 15:55:16.523053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from app.common.core.security import get_password_hash
from app.models import User

# revision identifiers, used by Alembic.
revision: str = '3296b4e43075'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def init_admin():
    # ### commands auto generated by Alembic - please adjust! ###
    # 初始化admin用户
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    # 2. 检查admin用户是否已存在，避免重复创建
    admin_user = session.query(User).filter_by(email='admin@bx.com').first()
    if not admin_user:
        # 3. 创建admin用户（根据你的User模型字段调整）
        hashed_password = get_password_hash('bx.123')
        admin_user = User(
            id='d2e96bf6-7273-11f0-8553-3c7c3f4b902b',
            email='admin@bx.com',
            hashed_password=hashed_password,  # 存储加密后的密码
            full_name='admin',
            is_active=True,
            is_superuser=True,  # 假设is_superuser标识超级管理员
        )
        session.add(admin_user)
        session.commit()
    session.close()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
    init_admin()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
